---
- name: Remove directories or files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ directories | sort(attribute='path', reverse=True) }}"
  when: item.state is defined and item.state == 'absent'

- name: Create/manage directories
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  with_items: "{{ directories | sort(attribute='path') }}"
  when: item.state is not defined or item.state != 'absent'
